#!/usr/bin/env python
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

modes = {
	'argparse':0,
	'trivia':1
}
mpd_host = {
	'host':'localhost',
	'port':'6600'
}
fortunes = [
	"A new friend helps you break out of an old routine",
	"Friends long absent are coming back to you.",
	"The time is right to make new friends.",
	"You may be hungry soon: order a takeout now.",
	"He who climbs a ladder must begin at the first step.",
	"You will travel to many places.",
	"You should be able to undertake and complete anything",
	"You will enjoy good health, you will be surrounded by luxury",
	"Do not hesitate to look for help, an extra hand should always be welcomed.",
	"Sometimes advice is what we ask for when we already know the answer.",
	"Sooner or later, those who win are those who think they can.",
	"We are here on the planet only once, and might as well get a feel for the place.",
	"Great works are performed not by strength, but by perseverance.",
	"People who are late are often happier than those who have to wait for them",
	"Present your best ideas today to an eager and welcoming audience.",
	"Every situation, properly perceived, becomes an opportunity.",
	"Things which matter most must never be at the mercy of things which matter least.",
	"Plan your work and work your plan.",
	"How can you have a beautiful ending without making beautiful mistakes?",
	"Humour is an affirmation of dignity.",
	"You will accept yourself.",
	"What's vice today may be virtue tomorrow.",
	"Make somebody happy today. Mind your own business.",
	"Be a generous friend and a fair enemy.",
	"Old friends, old wines and old gold are best",
	"If your desires are not extravagant, they will be granted",
	"Every Friend Joys in your Success",
	"Never quit!",
	"Dream lofty dreams, and as you dream, so shall you become.",
	"It's easier to fight for one's principles than to live up to them.",
	"The valor that struggles is better than the weakness that endures.",
	"There is only one success - to be able to spend life in your own way.",
	"Destiny is not a matter of chance; but a matter of choice.",
	"Reach high, for stars life hidden in your soul. Dream deep, for every dream precedes the goal.",
	"The world can only be grasped by action, not by contemplation.",
	"You get in life what you have the courage to ask for.",
	"Oh, what a tangled website we weave when first we practice.",
	"Good day for a change of scene. Repaper the bedroom wall.",
	"Do not live your life in fear, for if you do, you will never live your life",
	"We know who you are and we saw what you did last summer!",
	"Everything is going your way. There is little need for concern, as each path you choose will turn out to be the best one",
	"A momentary lapse in vigilance can lead to trouble. If you stay alert, you will eventually reach your goal.",
	"You will find something under the bed.",
	"even if you are on the right track, you will get run over if you just sit there.",
	"wag more, bark less.",
	"Heroes do while wannabes wait for the cameras to be watching...",
	"The harder you fall, the higher you bounce.",
	"the stars, in their infinite wisdom, recommend that you check yourself, as not doing so might lead you to wreck yourself.",
]
quotes = [
	"The leader seeks to communicate his vision to his followers.",
	"Half the people you know are below average.",
	"If you ain't makin' waves, you ain't kickin' hard enough!",
	"It's easier to fight for one's principles than to live up to them.",
	"The price of greatness is responsibility.",
	"There is always time to make right what is wrong.",
	"Right now there's an energy pushing you in a new direction.",
	"A well-aimed spear is worth three.",
	"You don't choose which path to take, but you will keep searching for the answers.",
	"When life gives you lemons; you paint them gold.",
	"If life gives you melons, you must be dyslexic.",
	"If you're going to get in trouble for hitting someone, might as well hit them hard.",
	"One size does not fit all.",
	"When you assume, you make an ass out of u and me.",
	"If explosives don't solve your problems; you aren't using enough.",
	"Predictably Unpredictable.",
	"Aspire to inspire before you expire.",
	"Knowledge is power, and power corrupts. So study hard and be evil.",
	"I am disappointment in you're grammar.",
	"I'll have a double cappuccino, half-caffeine, non-fat milk, with enough foam to be aesthetically pleasing, but not so much that it would leave a mustache.",
	"Don't sweat the petty things; and don't pet the sweaty things.",
	"The shinbone is a device for finding furniture in a dark room.",
	"A smile is like tight underwear... it makes your cheeks go up.",
	"I like work. It fascinates me. I sit and look at it for hours.",
	"When in doubt, mumble.",
	"A bus station is where a bus stops. A train station is where a train stops. On my desk, I have a work station.",
	"If you think nobody cares if you're alive, try missing a couple of payments.",
	"If your pants are on fire, being a liar becomes less important.",
	"Without geography, you're nowhere.",
	"The harder you fall, the higher you bounce.",
	"Eagles may soar in the clouds, but weasels never get sucked into jet engines.",
	"We should buy a fence and make people pay us two dollars to get in.",
	"You're slower than a herd of turtles stampeding through peanut butter.",
	"I was going to clean the apartment but had so many things on my 'to do' list that I decided to treat them all equally and draw pictures of sharks instead.",
	"I am currently away on leave, travelling through time and will be returning last week.",
	"The early bird gets the worm, but the second mouse gets the cheese.",
	"If the world didn't suck, we'd all fall off.",
	"The depressing thing about tennis is that no matter how good I get, I'll never be as good as a wall.",
	"There are three kinds of people; those who can count and those who can't.",
	"Before you criticize someone, you should walk a mile in their shoes. That way when you criticize them, you are a mile away from them and you have their shoes.",
	"If you're gonna be two-faced at least make one of them pretty.",
	"If you're drinking to forget, please pay in advance.",
	"I got food poisoning today. I don't know when I'll use it.",
	"Don't get your panties in a knot; it just makes you walk funny.",
	"Muffins are just ugly cupcakes.",
	"Don't judge a book by its fur.",
	"Your x-ray showed a broken rib, but we fixed it with Photoshop.",
	"You can pay for school but you can't buy class.",
	"People aren't either wicked or noble. They're like chef's salads, with good things and bad things chopped and mixed together in a vinaigrette of confusion and conflict.",
	"A day without sunshine is like, you know, night.",
	"It takes skills to trip over flat surfaces.",
	"You don't have to be crazy to work here. They'll train you.",
	"Squares and Triangles Agree: Circles are Pointless.",
	"Why be difficult when with a bit of effort you can be impossible?",
	"When choosing between two evils, I always like to try the one I've never tried before.",
	"I eat lightning and crap thunder.",
	"I'd like to help you out. Which way did you come in?",
	"Warning: Dates in Calendar are closer than they appear.",
	"When you don't know what to do, walk fast and look worried.",
	"Your first instinct will be to run, while your second instinct will be to find your legs.",
	"you'll finally get into shape this week, though which one exactly, isn't clear yet.",
	"it is said that the eyes are the windows to one's soul, which helps explain why so many damn birds keep flying into them.",
	"first you take a drink, then the drink takes a drink, then the drink takes you.",
	"even if you are on the right track, you will get run over if you just sit there.",
	"wag more, bark less.",
	"I never forget a face, but in your case I'll be glad to make an exception.",
	"if at first you don't succeed, then skydiving definitely isn't for you.",
	"the brain is a wonderful organ; it starts working the moment you get up in the morning, and does not stop until you get into the office",
	"the shortest distance between two points is under construction.",
	"the less they think, the more they talk.",
	"I'd love to trade Caller I.D. for Caller I.Q.",
	"you can try dancing around the issue all you want, but in the end, you still don't know what to do with your arms while on the dance floor.",
	"you will come face to face with your worst fears this week after standing in front of a bathroom mirror.",
	"Advances in science will soon allow man to travel to the most distant corners of the universe. Still no word, however, on it being able to get you off that couch.",
	"I owe, I owe, so it's off to work I go.",
	"Energizer Bunny arrested, charged with battery.",
	"Silence is golden, but duct tape is silver.",
	"your eyes are like diamonds and your teeth are like glass but your face reminds me of king kong's ass.",
	"I'm not confused. I'm just well mixed.",
	"how old would you be if you didn't know how old you are?",
	"there's nothing better than a long hot shower to wash away all of your worries; except for my bills.They keep clogging the drain.",
	"I like nonsense, it wakes up the brain cells.",
	"always forgive your enemies; nothing annoys them more.",
	"The statistics on sanity are that one out of every four people is suffering from a mental illness. Look at your 3 close friends. If they're ok, then it's you.",
	"I love deadlines. I like the whooshing sound they make as they go by.",
	"thinking about thinking but thinks thinking would be a bad thing to think about thinking so thinks I should stop thinking about thinking.",
	"you look like I could use a drink.",
	"if there's an umbrella in my drink, it better be raining.",
	"Time flies like an arrow; fruit flies like a banana.",
	"a lie can travel halfway around the world while the truth is putting on its shoes.",
	"beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.",
	"I like your approach. Now let's see your departure.",
	"Some people are like slinkies; not really good for anything, but they bring a smile to your face when pushed down the stairs.",
	"it takes a lot more to be unhappy.",
	"I didn't slap you, I simply high fived your face.",
	"If you ain't makin' waves, you ain't kickin' hard enough!",
	"When life gives you lemons; you paint them gold.",
	"If life gives you melons, you must be dyslexic.",
	"If you're going to get in trouble for hitting someone, might as well hit them hard.",
	"One size does not fit all.",
	"When you assume, you make an ass out of u and me.",
	"If explosives don't solve your problems; you aren't using enough.",
	"Predictably Unpredictable.",
	"Aspire to inspire before you expire.",
	"Knowledge is power, and power corrupts. So study hard and be evil.",
	"I am disappointment in you're grammar.",
	"I'll have a double cappuccino, half-caffeine, non-fat milk, with enough foam to be aesthetically pleasing, but not so much that it would leave a mustache.",
	"Don't sweat the petty things; and don't pet the sweaty things.",
	"The shinbone is a device for finding furniture in a dark room.",
	"A smile is like tight underwear...it makes your cheeks go up.",
	"I like work. It fascinates me. I sit and look at it for hours.",
	"When in doubt, mumble.",
	"A bus station is where a bus stops. A train station is where a train stops. On my desk, I have a work station.",
	"If you think nobody cares if you're alive, try missing a couple of payments.",
	"If your pants are on fire, being a liar becomes less important.",
	"Without geography, you're nowhere.",
	"Eagles may soar in the clouds, but weasels never get sucked into jet engines.",
	"We should buy a fence and make people pay us two dollars to get in.",
	"You're slower than a herd of turtles stampeding through peanut butter.",
	"I was going to clean the apartment but had so many things on my 'to do' list that I decided to treat them all equally and draw pictures of sharks instead.",
	"I am currently away on leave, travelling through time and will be returning last week.",
	"The early bird gets the worm, but the second mouse gets the cheese.",
	"If the world didn't suck, we'd all fall off.",
	"The depressing thing about tennis is that no matter how good I get, I'll never be as good as a wall.",
	"There are three kinds of people; those who can count and those who can't.",
	"Before you criticize someone, you should walk a mile in their shoes. That way when you criticize them, you are a mile away from them and you have their shoes.",
	"If you're gonna be two-faced at least make one of them pretty.",
	"If you're drinking to forget, please pay in advance.",
	"I got food poisoning today. I don't know when I'll use it.",
	"Don't get your panties in a knot; it just makes you walk funny.",
	"Muffins are just ugly cupcakes.",
	"Don't judge a book by its fur.",
	"Your x-ray showed a broken rib, but we fixed it with Photoshop.",
	"If I was as ugly as you were, I wouldn't say Hi to others, I'd say BOO!",
	"You can pay for school but you can't buy class.",
	"People aren't either wicked or noble. They're like chef's salads, with good things and bad things chopped and mixed together in a vinaigrette of confusion and conflict.",
	"A day without sunshine is like, you know, night.",
	"It takes skills to trip over flat surfaces.",
	"You don't have to be crazy to work here. They'll train you.",
	"Squares and Triangles Agree: Circles are Pointless.",
	"Why be difficult when with a bit of effort you can be impossible?",
	"When choosing between two evils, I always like to try the one I've never tried before.",
	"I eat lightning and crap thunder.",
	"I'd like to help you out. Which way did you come in?",
	"Warning: Dates in Calendar are closer than they appear.",
	"On the other hand, you have different fingers.",
	"When you don't know what to do, walk fast and look worried.",
	"Your first instinct will be to run, while your second instinct will be to find your legs.",
	"Make somebody happy today. Mind your own business.",
	"Drink coffee; do stupid things faster with more energy!",
	"the stars, in their infinite wisdom, recommend that you check yourself, as not doing so might lead you to wreck yourself.",
	"you'll finally get into shape this week, though which one exactly, isn't clear yet.",
	"it is said that the eyes are the windows to one's soul, which helps explain why so many damn birds keep flying into them.",
	"first you take a drink, then the drink takes a drink, then the drink takes you.",
	"I never forget a face, but in your case I'll be glad to make an exception.",
	"if at first you don't succeed, then skydiving definitely isn't for you.",
	"the brain is a wonderful organ; it starts working the moment you get up in the morning, and does not stop until you get into the office",
	"the shortest distance between two points is under construction.",
	"the less they think, the more they talk.",
	"I'd love to trade Caller I.D. for Caller I.Q.",
	"you can try dancing around the issue all you want, but in the end, you still don't know what to do with your arms while on the dance floor.",
	"you will come face to face with your worst fears this week after standing in front of a bathroom mirror.",
	"Advances in science will soon allow man to travel to the most distant corners of the universe. Still no word, however, on it being able to get you off that couch.",
	"I owe, I owe, so it's off to work I go.",
	"Energizer Bunny arrested, charged with battery.",
	"Silence is golden, but duct tape is silver.",
	"your eyes are like diamonds and your teeth are like glass but your face reminds me of king kong's ass.",
	"I'm not confused. I'm just well mixed.",
	"how old would you be if you didn't know how old you are?",
	"there's nothing better than a long hot shower to wash away all of your worries; except for my bills.They keep clogging the drain.",
	"I like nonsense, it wakes up the brain cells.",
	"always forgive your enemies; nothing annoys them more.",
	"The statistics on sanity are that one out of every four people is suffering from a mental illness. Look at your 3 close friends. If they're ok, then it's you.",
	"I love deadlines. I like the whooshing sound they make as they go by.",
	"thinking about thinking but thinks thinking would be a bad thing to think about thinking so thinks I should stop thinking about thinking.",
	"you look like I could use a drink.",
	"if there's an umbrella in my drink, it better be raining.",
	"Time flies like an arrow; fruit flies like a banana.",
	"A lie can travel halfway around the world while the truth is putting on its shoes.",
	"beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.",
	"I like your approach. Now let's see your departure.",
	"some people are like slinkies; not really good for anything, but they bring a smile to your face when pushed down the stairs.",
	"it takes a lot more to be unhappy.",
	"I didn't slap you, I simply high fived your face."
]
fmls = [
	"Today, it was my wedding day, and while I was standing next to my husband in front of all of our guests, I was rocking on my heels because I was nervous. I rocked too far and fell backward. My husband didn't come to help me up. He just said at the top of his lungs, 'FAIL!' FML",
	"Today, I tried whitening my teeth with an off-brand product. It didn't whiten my teeth, but it did burn parts of my gums off. FML",
	"Today, I drunkenly staggered home and crashed on the couch. When I woke up I realized it wasn't my house. FML",
	"Today, my five year old daughter came up to me and asked, \"Mom, why are we so poor?\" I replied, in a sweet motherly tone \"Honey, we're not poor.\" She then asked, \"Then why do you dress like we are poor?\" FML",
	"Today, my flatmate was listening to opera on full volume all afternoon and now he's playing James Bond on the trumpet. FML",
	"Today, while mowing the lawn, I ran over a hornet's nest. FML",
	"Today, I was practising the violin in my apartment. A man knocks on the door and introduces himself with a smile, says he wants to know my \"schedule.\" I reply, \"I'm pretty busy but maybe we could get a drink sometime.\" To which he retorts, \"No, I just want to know when you'll stop.\" FML",
	"Today, my girlfriend of four years friend-zoned me while I was proposing to her. FML",
	"Today, my boyfriend and I started our diet. After a long day of being held accountable for every calorie I ate, I went home to sneak a snack. My boyfriend came over to surprise me, and found me on the couch shoveling left-over Indian food into my mouth. FML",
	"Today, I was running the 100m sprint in a track meet. Me and another girl were tied for dead last. When we finished, she complained, \"It's so embarrassing how slow I am today. I have shin splints. What happened to you?\" I was actually running my hardest. FML",
	"Today, during a slow dance, my date wrapped his arms around my waist. Right as I touched his neck he says, \"Sorry, I'm slightly sweaty.\" He wasn't lying. For the longest two minutes of my life I was swimming in his sweat. FML",
	"Today, my 4 year-old daughter's favorite expression became \"shit balls.\" FML",
	"Today, I found out my brother blew chunks into the inside of my jeans. How did I find this out? I put them on. FML",
	"Today, I learned that my mother now refuses to drink anything but bottled water because she actually believes that the government is putting a chemical in tap water that lowers pregnancy rates. She is trying for her 5th child. FML",
	"Today, I went on a date with a woman. She brought along her stuffed rabbit, and introduced us. FML",
	"Today, I attended the wrong funeral. I spent twenty minutes trying to hide and walk away without being too conspicuous. FML",
	"Today, I made it my life goal to own a towel heater. FML",
	"Today, my parents went out of town and I was home all alone. I put up party decorations such as streamers, balloons and confetti. Then, I drank out of red cups, crushed them up and put them all over the house. I didn't have a party, I just wanted to convince my family that I'm not a loser. FML",
	"Today, I thought I was home alone, so I started singing to my cat. After a half hour of this, I finally stopped. Then I heard applauding. I turned around to find my parents standing in my doorway. FML",
	"Today, my father decided to \"prepare\" me for the real world by telling me that I'm ugly. FML",
	"Today, my younger brother brought home his new bagpipes. My older brother plays the drums. I'm currently preparing to sit the most important exams of my schooling life. FML",
	"Today, I learned that several thousand people in my state got tickets this month for driving and talking on the phone. My mom called to tell me this while I was driving. I'm now part of that statistic. Thanks, mom. FML",
	"Today, I have two black eyes. The first one I got from the girl whose ass I mistakenly grabbed at a party last night. The other one I got from my girlfriend when I explained the first one. FML",
	"Today, my friend asked me if I could watch her mother's cats while they go on vacation. I agreed since her house is on my way to work. When I talked to her mother, I found out she has 30-something cats. She reckons she lost count. FML",
	"Today, I was kicked out of a Family Dollar. My mom thought it would be fun to press all the buttons on the musical ceramic cathedrals so they would all play at the same time. FML",
	"Today, while I was mowing the lawn in my backyard, I ran over a glass bottle. My legs looked like a disco ball. FML",
	"Today, I caught my pregnant wife smoking. This is after I quit over a month ago to show her my support and be a good influence on our child. FML",
	"Today, my co-worker came back from Thailand with big new breasts. She told me to go ahead and touch them because they have a funny texture for the first few months. When our GM entered the room, I had both hands down my co-worker's shirt, agreeing that they were unnaturally firm. FML",
	"Today, I was getting off of work, talking to my boss and I asked if I could get a ride home, since my usual ride was too lazy to come get me. He said, sure, but to be really careful since he just had his car detailed. I was getting in the car, tripped and threw my hot cocoa all inside of his car. FML",
	"Today, my favorite fish died. To make things better my parents thought to take me out to dinner. We ate sushi. FML",
	"Today, I asked my mother if she thought my cat was getting fat. She replied \"It's not the cat you should worry about\". FML",
	"Today, I was going home with the tomato plant I just bought in my cup holder. The smell of it was filling the car and I love the smell so I picked it up and took a wiff. A few moments later I got pulled over. Apparantly, the cop saw me sniff it and thought I was smelling a marijuana plant. FML",
	"Today, we got our yearbooks for school. I opened to my profile to see that they misspelled my first name which is James. They wrote Lames. FML",
	"Today, my math teacher told me to learn how to say \"welcome to wal-mart\". FML",
	"Today, I was out drinking with some friends in a Safeway parking lot, when I saw a familiar-looking vehicle pull up beside us. It was my dad, who angrily got out and demanded that I come home. I'm twenty-four, and now the laughingstock of my social circle. FML",
	"Today, I came back to my apartment to see that my roommate had left out bread, deli meat, and cheese on the counter, and made myself a sandwich. When she came back, she informs me that she found bugs in the fridge and took out all the food she thought would be contaminated. FML",
	"Today, I bit into a Reese's Cup that had been sitting on my desk for a while. As I did, half of a yellow meal worm fell out and landed in front of me, the other half was in my mouth. It was wiggling. FML",
	"Today, I was woken up by my 5 year old daughter hitting me with a pillow because she had a dream that I was using her tooth brush on the dog. We don't have a dog. She is now refusing to brush her teeth. FML",
	"Today, I found out that if you don't clean the inside of your sonicare toothbrush, it can grow masses of fungus. I've been brushing my teeth with a vibrating mushroom for the past 5 months. FML",
	"Today, I learned the hard way that if you're going to pour bleach on bugs to kill them, you need to be prepared for them to fly up and try to attack your face. FML",
	"Today, I tried to close my desk drawer by hitting it with my hip, like they do in the movies. Everything on my desk fell off. FML",
	"Today, I was late for the bus. I chased after it for 3 blocks until I realized that the bus driver was laughing at me trying to catch her. FML",
	"Today, after finally getting a job offer after months of unemployment, I found out that the person who was going to hire me got fired. Which means I'm not getting the job. FML",
	"Today, my friends thought it would be a good idea to make fun of a homeless man. I didn't fancy making fun of the less fortunate, so I stayed a bit back. Still, the homeless man didn't think it would matter to throw a rock at me after my buddies ran away. FML",
	"Today, I was expecting a very important work call. Today was also the day I got insuppressible diarrhea. As I was running to the washroom, the phone rang. I didn't make it to the washroom or the phone. FML",
	"Today, my book bag was so heavy that it set off my car's passenger detection system in the front seat. I had to buckle in my textbooks. FML",
	"Today, I cleaned out my house and placed multiple boxes of clothes and books in my two-seated truck to take to the Goodwill. While turning onto the highway, everything tumbled on top of me, sending me crashing into a guardrail. FML",
	"Today, I brought my girlfriend of four months home for dinner to meet my parents. The first thing my mom says to her? \"Oh my God, you're real!\" FML",
	"Today, I had a job interview for a job I've been dying to have. As I'm walking into the office, the manager says, \"Aren't you my son's ex, the one he cheated on?\" All I could do was sit there quietly as he laughed at me. FML",
	"Today, I took a shower at my friend's house. The shampoo smelled really good that I asked my friend where she bought it so I could get one also. Her reply? Petco. I just washed my hair with dog shampoo. FML",
	"Today, my wife and I were planning our nursery for our future child. She said that we'd be painting it pink either way. I asked what would happen if we had a boy. She said \"Oh, he'll be gay\" with a menacing glare. I'm worried. FML",
]
tolds = [
	"TOLDASAURUS REX",
	"Cash4told.com",
	"No country for told men",
	"Knights of the told Republic",
	"ToldSpice",
	"The Elder Tolds IV: Oblivious",
	"Command & Conquer: Toldberian Sun",
	"GuiTold Hero: World Told",
	"Told King of Boletaria",
	"Countold Strike",
	"Unreal Toldament",
	"Stone-told Steve Austin",
	"Half Life 2: Episode Told",
	"World of Warcraft: Catoldclysm",
	"Roller Coaster Toldcoon",
	"Assassin's Creed: Tolderhood",
	"Battletolds",
	"S.T.A.L.K.E.R.: Shatold of Chernobyl",
	"Toldasauraus Rex 2: Electric Toldaloo",
	"Told of Duty 4: Modern Toldfare",
	"Pokemon Told and Silver",
	"The Legend of Eldorado : The Lost City of Told",
	"Rampage: Toldal Destruction",
	"Told Fortress Classic",
	"Toldman: Arkham Told",
	"The Good, The Bad, and The Told",
	"Super Mario SunTold",
	"Legend of Zelda: Toldacarnia of Time",
	"Toldstone creamery",
	"Mario Golf: Toldstool Tour",
	"Super Told Boy",
	"Left 4 Told",
	"Battoldfield: Bad Company 2",
	"Toldman Sachs",
	"Conker's Bad Fur Day: Live and Retolded",
	"Lead and Told: Gangs of the Wild West",
	"Portold 2",
	"Avatold: The Last Airbender",
	"Dragon Ball Z Toldkaichi Budokai",
	"Toldcraft II: Tolds of Toldberty",
	"Leo Toldstoy",
	"Metal Gear Toldid 3: Snake Eater",
	"J.R.R Toldkien's Lord of the Told",
	"Told you that ps3 has no games",
	"LitTOLD Big Planet",
	"Rome: Toldal War",
	"Gran Toldrismo 5",
	"Told Calibur 4",
	"Told Fortress 2",
	"Castlevania: RonTold of Blood",
	"Guilty Gear XX Accent Told",
	"Cyndaquil, Chicorita, and Toldodile",
	"was foretold",
	"Demon's Told",
	"youtold.com",
	"Tolden Sun: Dark Dawn",
	"Tic-Tac-Told",
	"Biotold 2",
	"Toldbound",
	"icetold",
	"Told of the Rings"
]
trivias = {
	'misc':[
		['A phobia characterized by a fear of blood?', 'Hemophobia'],
		['What is a more common name in this country for an item originally called an "India rubber"?', 'eraser'],
		['What is the fastest land animal in the world?', 'Cheetah'],
		['Is a dolphin a mammal?', 'Yes'],
		['What is converted into alcohol during brewing?', 'Sugar'],
		['If cats are feline, what are sheep?', 'Ovine'],
		['What is the other name for Wildebeest?', 'GNU'],
	],
	'a':[
		['What was the first James Bond novel?', 'Casino Royale'],
		['What popular operating system are the Mac OS X series based on?', 'Unix'],
		["What chess piece has a horse's head?", 'Knight'],
		['What was the first US city to have a public school system?', 'Boston'],
		['What does NATO stand for?', 'North Atlantic Treaty Organization'],
	],
	'b':[
		['What is the name for a human third molar?', 'Wisdom Tooth'],
		['What playing card symbolizes death?', 'Ace of spades'],
		['The Himalayas are located on which continent?', 'Asia'],
		['Basic Brich?', 'Sarah'],
		['When was the Red Bull energy drink first introduced?', '1987'],
	],
	'c':[	
		['What do whales feed their young?', 'Milk'],
		['What animated movie takes its name from a Yiddish word meaning monster?', 'Shrek'],
		['What is the device that measures the number of steps you take when walking or running?', 'Pedometer'],
		['What is the main ingredient in glass?', 'Sand'],
		['The title of the final "A Song of Ice and Fire" novel will be...?', 'A Dream of Spring'],
	],
	'd':[
		['Which country has the longest coastline?', 'Canada'],
		['What is heaven to fallen Norse warriors?', 'Valhalla'],
		['What name was given to people who made illegal booze during prohibition?', 'Bootleggers'],
		['What is the strongest muscle in the human body?', 'Tongue'],
		['The folklore characters known as "oni" originated in which country?', 'Japan'],
	],
	'e':[
		['What year was the movie "Titanic" released?', '1997'],
		['Which Spice girl was the only one named after a spice?', 'Ginger'],
		['What slogan did Nancy Reagan create for her drug awareness campaign?', 'Just Say No'],
		['Which British prime minister was awarded the Nobel Prize for Literature?', 'Winston Churchill'],
		['Who directed the 1996 movie "Mars Attacks!"?', 'Tim Burton'],
	],
	'gameofthrones':[
		['In "A Song of Ice and Fire" what is the motto of House Lannister?', 'Hear Me Roar'],
		['Characters in the show derisively refer to Tyrion Lannister as "The ____"', 'Imp'],
		['What is the name of the youngest Stark child?', 'Rickon'],
		['What is the Dothraki word for "thank you"?', 'none'],
		['Game of Thrones is set in the fictional land of Westeros. How many Kingdoms does it have?', '7'],
	],
}
links = [
	'https://www.shippingsoon.com',
	'http://www.mylesburke.net',
	'http://www.joeygrasso.com',
	'http://www.pageben.com',
	'http://www.dracsoft.com',
	'http://www.calebsuttles.com',
	'http://www.livinmoti.com',
	'http://robincrockett.writersresidence.com',
	'Basic Brich: http://WWW.SARAHLEIGHBRICH.COM'
]
VERSION = 'Vada v0.7'
COPYRIGHT = 'GNU General Public License v3.0 - All Rights Reversed'

#Copyright 2014 Shippingsoon - All Rights Reserved
